name: domain
description: "Domain layer of the app"
#version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

resolution:
  workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: