name: ui

environment:
  sdk: ^3.9.2
  flutter:

dependencies:
  flutter:
    sdk: flutter

  lucide_icons_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

resolution:
  workspace

flutter: