name: feature_auth

environment:
  sdk: ^3.9.2
  flutter:

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../../domain
  ui:
    path: ../../ui
  util:
    path: ../../util

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

resolution:
  workspace

flutter: